/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d1086fdf311412fe6ea5f2c
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { MessageService } from '../../services/message.service';
// Import Models
import { Message } from '../../domain/chat_db/message';

// START - USED SERVICES
/**
* MessageService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* MessageService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Message
 * @class MessageListComponent
 */
@Component({
    selector: 'app-message-list',
    templateUrl: './message-list.component.html',
    styleUrls: ['./message-list.component.css']
})
export class MessageListComponent implements OnInit {
    list: Message[];
    search: any = {};
    idSelected: string;
    constructor(
        private messageService: MessageService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.messageService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Message to remove
     *
     * @param {string} id Id of the Message to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Message
     */
    deleteItem() {
        this.messageService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
